### PR TITLE
fix: ignore all non-http[s] links

### LINKED ISSUE #104: Ignore all protocols except HTTP and HTTPS
We've been running around adding specific protocol handlers to ignore.  Instead ... the library should only attempt to crawl HTTP or HTTPS links.

### PR DESCRIPTION
**Pull request by JustinBeckwith**
Fixes #104

### CODE REVIEW

File: test/test.ts [hunk 1]
```diff
@@ -110,7 +110,7 @@ describe('linkinator', () => {
       path: 'test/fixtures/recurse',
       recurse: true,
     });
-    assert.strictEqual(results.links.length, 5);
+    assert.strictEqual(results.links.length, 4);
```
Comment (JustinBeckwith) [inline test/test.ts]: Turns out this was a bug!  The cache was not normalizing the url for `/index` style paths, which the new `URL` object does 😄
